# Generated by Django 2.0.3 on 2018-04-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180422_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='quest',
        ),
    ]
