# Generated by Django 2.0.3 on 2018-04-23 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemixin',
            name='negative_votes',
            field=models.ManyToManyField(null=True, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votemixin',
            name='positive_votes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
