# Generated by Django 2.0.3 on 2018-04-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180423_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votemixin',
            old_name='positive_votes',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='votemixin',
            name='negative_votes',
        ),
        migrations.AddField(
            model_name='votemixin',
            name='value',
            field=models.NullBooleanField(),
        ),
    ]
